import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

// Chatbot Styles
export const chatStyles = StyleSheet.create({
  chatContainer: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    zIndex: 1000,
  },
  chatWindow: {
    width: width * 0.85,
    height: height * 0.6,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  chatHeader: {
    backgroundColor: '#8B5CF6',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  headerRight: {
    flexDirection: 'row',
    gap: 8,
  },
  headerButton: {
    padding: 4,
    borderRadius: 4,
  },
  messagesList: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  messageContainer: {
    marginBottom: 12,
  },
  userMessageContainer: {
    alignItems: 'flex-end',
  },
  botMessageContainer: {
    alignItems: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
  },
  userMessage: {
    backgroundColor: '#a57ffeff',
    borderBottomRightRadius: 4,
  },
  botMessage: {
    backgroundColor: '#F3F4F6',
    borderBottomLeftRadius: 4,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 18,
  },
  userMessageText: {
    color: '#fdfafaff',
  },
  botMessageText: {
    color: '#374151',
  },
  messageTime: {
    fontSize: 11,
    marginTop: 4,
  },
  userMessageTime: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  botMessageTime: {
    color: '#9CA3AF',
  },
  inputContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    alignItems: 'flex-end',
    gap: 8,
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    maxHeight: 100,
  },
  sendButton: {
    backgroundColor: '#8B5CF6',
    padding: 10,
    borderRadius: 20,
  },
  minimizedChat: {
    position: 'absolute',
    bottom: 20,
    top:-55,
    right: 20,
    width: 56,
    height: 56,
    backgroundColor: '#6B4EAE',
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 1000,
    marginRight: '3%',
    borderWidth: 2,
    borderColor: '#6B4EAE',
    transform: [{ scale: 1 }],
  },
  minimizedText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  chatToggle: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    backgroundColor: '#6B4EAE',
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 1000,
    marginRight: '3%',
    borderWidth: 2,
    borderColor: '#6B4EAE',
    transform: [{ scale: 1 }],
  },
  chatToggleInner: {
    position: 'absolute',
    width: 48,
    height: 48,
    backgroundColor: '#7156b0ff',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ scale: 0.85 }],
  },
  chatToggleRipple: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: '#d7c8f9ff',
    opacity: 0.5,
  },
});
